CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "ShopName" text NOT NULL,
    "Location" text NOT NULL,
    "OwnerId" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE aisummaries (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    summary_text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_aisummaries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_aisummaries_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    name character varying(100) NOT NULL,
    "TestColumn123" text,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_categories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    name character varying(255) NOT NULL,
    phone_number character varying(20),
    whatsapp_number character varying(20),
    website character varying(255),
    email character varying(255),
    contact_person character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT suppliers_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_suppliers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    name character varying(100) NOT NULL,
    sku text,
    barcode text,
    description text,
    brand text,
    supplier_id integer,
    sellingprice numeric(10,2) NOT NULL,
    costprice numeric(10,2) NOT NULL,
    taxpercentage numeric(5,2) NOT NULL,
    quantity integer NOT NULL,
    minquantity integer NOT NULL,
    createddate timestamp with time zone NOT NULL DEFAULT (NOW()),
    updateddate timestamp with time zone NOT NULL DEFAULT (NOW()),
    isactive boolean NOT NULL DEFAULT TRUE,
    category_id integer,
    CONSTRAINT items_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_items_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT fk_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT items_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE purchase_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    supplier_id integer NOT NULL,
    status character varying(50) NOT NULL,
    order_date timestamp with time zone NOT NULL,
    expected_date timestamp with time zone,
    CONSTRAINT "PK_purchase_orders" PRIMARY KEY (id),
    CONSTRAINT "FK_purchase_orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT fk_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT
);

CREATE TABLE itemhistories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    itemid integer NOT NULL,
    transactiontype text NOT NULL,
    quantitychanged integer NOT NULL,
    remarks text,
    timestamp timestamp with time zone NOT NULL DEFAULT (NOW()),
    username text,
    CONSTRAINT itemhistories_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_itemhistories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT fk_item FOREIGN KEY (itemid) REFERENCES items (id) ON DELETE CASCADE
);

CREATE TABLE sales (
    sale_id integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    item_id integer NOT NULL,
    quantity_sold integer NOT NULL,
    sale_price_at_time_of_sale numeric(10,2) NOT NULL,
    cost_price_at_time_of_sale numeric(10,2) NOT NULL,
    sale_timestamp timestamp with time zone NOT NULL,
    CONSTRAINT "PK_sales" PRIMARY KEY (sale_id),
    CONSTRAINT "FK_sales_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_sales_items_item_id" FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);

CREATE TABLE purchase_order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity_ordered integer NOT NULL,
    CONSTRAINT "PK_purchase_order_items" PRIMARY KEY (id),
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) ON DELETE CASCADE
);

CREATE INDEX "IX_aisummaries_UserId" ON aisummaries ("UserId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_categories_UserId" ON categories ("UserId");

CREATE INDEX "IX_itemhistories_itemid" ON itemhistories (itemid);

CREATE INDEX "IX_itemhistories_UserId" ON itemhistories ("UserId");

CREATE INDEX "IX_items_category_id" ON items (category_id);

CREATE INDEX "IX_items_supplier_id" ON items (supplier_id);

CREATE INDEX "IX_items_UserId" ON items ("UserId");

CREATE INDEX "IX_purchase_order_items_item_id" ON purchase_order_items (item_id);

CREATE INDEX "IX_purchase_order_items_purchase_order_id" ON purchase_order_items (purchase_order_id);

CREATE INDEX "IX_purchase_orders_supplier_id" ON purchase_orders (supplier_id);

CREATE INDEX "IX_purchase_orders_UserId" ON purchase_orders ("UserId");

CREATE INDEX "IX_sales_item_id" ON sales (item_id);

CREATE INDEX "IX_sales_UserId" ON sales ("UserId");

CREATE INDEX "IX_suppliers_UserId" ON suppliers ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250916171915_InitialDatabaseCreation', '9.0.7');

COMMIT;

